import type { NormalizedListing } from '@carmatch/shared'

/**
 * DEMO-DATEN — ausschließlich für Entwicklung und Tests.
 * Alle Einträge sind fiktive Inserate mit realistischen technischen Daten.
 * Bilder sind Platzhalter (imagesAreDemo: true) und werden in der UI als Demo gekennzeichnet.
 * In Produktion ist dieser Provider gesperrt (siehe config.ts).
 */

type Demo = Omit<NormalizedListing, 'provider' | 'currency' | 'isAvailable' | 'imagesAreDemo'>

function img(label: string): string[] {
  const text = encodeURIComponent(label)
  return [
    `https://placehold.co/800x500/17181c/f4f2ee/png?text=${text}`,
    `https://placehold.co/800x500/26272c/f4f2ee/png?text=${text}+%E2%80%94+Interieur`,
  ]
}

export const demoListings: Demo[] = [
  {
    providerListingId: 'demo-0001',
    make: 'BMW', model: 'M340i', variant: 'xDrive Touring', title: 'BMW M340i xDrive Touring',
    price: 54900, year: 2021, firstRegistration: '2021-06', mileage: 48200,
    powerKw: 275, powerHp: 374, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'WAGON', doors: 5, seats: 5, color: 'Portimao Blau', interior: 'Leder Schwarz',
    features: ['AHK', 'HUD', 'Harman Kardon', 'Laserlicht', 'ACC'], consumptionL100: 8.1, co2GKm: 185,
    displacementCcm: 2998, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-06',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('BMW M340i Touring'), sellerType: 'DEALER', dealerName: 'Autohaus Ostsee Rostock',
    latitude: 54.0924, longitude: 12.1407, postalCode: '18055', city: 'Rostock', country: 'DE',
  },
  {
    providerListingId: 'demo-0002',
    make: 'Volkswagen', model: 'Golf', variant: 'GTI Clubsport', title: 'VW Golf 8 GTI Clubsport',
    price: 36990, year: 2022, firstRegistration: '2022-03', mileage: 31000,
    powerKw: 221, powerHp: 300, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'FWD',
    bodyType: 'HATCHBACK', doors: 5, seats: 5, color: 'Moonstone Grau', interior: 'Stoff/ArtVelours',
    features: ['DCC', 'Akrapovic', 'Matrix-LED'], consumptionL100: 7.5, co2GKm: 170,
    displacementCcm: 1984, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-03',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('VW Golf GTI Clubsport'), sellerType: 'DEALER', dealerName: 'VW Zentrum Schwerin',
    latitude: 53.6355, longitude: 11.4012, postalCode: '19053', city: 'Schwerin', country: 'DE',
  },
  {
    providerListingId: 'demo-0003',
    make: 'Porsche', model: '718 Cayman', variant: 'T', title: 'Porsche 718 Cayman T',
    price: 62500, year: 2020, firstRegistration: '2020-09', mileage: 39500,
    powerKw: 220, powerHp: 300, fuelType: 'PETROL', transmission: 'MANUAL', drivetrain: 'RWD',
    bodyType: 'COUPE', doors: 2, seats: 2, color: 'GT-Silber', interior: 'Leder/Sport-Tex',
    features: ['PASM', 'Sport Chrono', 'Apple CarPlay'], consumptionL100: 8.9, co2GKm: 205,
    displacementCcm: 1988, previousOwners: 2, accidentFree: true, inspectionValidUntil: '2026-09',
    fullServiceHistory: true, warranty: false, financingAvailable: true,
    images: img('Porsche 718 Cayman T'), sellerType: 'DEALER', dealerName: 'Sportwagenzentrum Hamburg',
    latitude: 53.5511, longitude: 9.9937, postalCode: '20095', city: 'Hamburg', country: 'DE',
  },
  {
    providerListingId: 'demo-0004',
    make: 'Audi', model: 'A4 Avant', variant: '40 TDI quattro S line', title: 'Audi A4 Avant 40 TDI quattro',
    price: 33900, year: 2020, firstRegistration: '2020-11', mileage: 78400,
    powerKw: 150, powerHp: 204, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'WAGON', doors: 5, seats: 5, color: 'Daytonagrau', interior: 'Leder/Alcantara',
    features: ['Virtual Cockpit', 'AHK', 'Matrix-LED', 'ACC'], consumptionL100: 5.2, co2GKm: 137,
    displacementCcm: 1968, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-11',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Audi A4 Avant TDI'), sellerType: 'DEALER', dealerName: 'Audi Partner Lübeck',
    latitude: 53.8655, longitude: 10.6866, postalCode: '23552', city: 'Lübeck', country: 'DE',
  },
  {
    providerListingId: 'demo-0005',
    make: 'Mazda', model: 'MX-5', variant: '2.0 Skyactiv-G Exclusive', title: 'Mazda MX-5 RF 2.0',
    price: 27800, year: 2021, firstRegistration: '2021-05', mileage: 22100,
    powerKw: 135, powerHp: 184, fuelType: 'PETROL', transmission: 'MANUAL', drivetrain: 'RWD',
    bodyType: 'CONVERTIBLE', doors: 2, seats: 2, color: 'Soul Red', interior: 'Leder Schwarz',
    features: ['Bose', 'LED', 'Recaro-Sitze'], consumptionL100: 6.9, co2GKm: 156,
    displacementCcm: 1998, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-05',
    fullServiceHistory: true, warranty: true, financingAvailable: false,
    images: img('Mazda MX-5 RF'), sellerType: 'PRIVATE',
    latitude: 54.3091, longitude: 13.0818, postalCode: '18435', city: 'Stralsund', country: 'DE',
  },
  {
    providerListingId: 'demo-0006',
    make: 'Skoda', model: 'Octavia Combi', variant: '2.0 TDI Style', title: 'Skoda Octavia Combi 2.0 TDI',
    price: 24490, year: 2021, firstRegistration: '2021-02', mileage: 89900,
    powerKw: 110, powerHp: 150, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'FWD',
    bodyType: 'WAGON', doors: 5, seats: 5, color: 'Mondweiß', interior: 'Stoff Grau',
    features: ['AHK', 'ACC', 'Canton'], consumptionL100: 4.8, co2GKm: 126,
    displacementCcm: 1968, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-02',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Skoda Octavia Combi'), sellerType: 'DEALER', dealerName: 'Skoda Autohaus Wismar',
    latitude: 53.8914, longitude: 11.4525, postalCode: '23966', city: 'Wismar', country: 'DE',
  },
  {
    providerListingId: 'demo-0007',
    make: 'Tesla', model: 'Model 3', variant: 'Long Range AWD', title: 'Tesla Model 3 Long Range',
    price: 32900, year: 2021, firstRegistration: '2021-08', mileage: 61200,
    powerKw: 324, powerHp: 441, fuelType: 'ELECTRIC', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'SEDAN', doors: 4, seats: 5, color: 'Pearl White', interior: 'Vegan Schwarz',
    features: ['Autopilot', 'Wärmepumpe', 'AHK'], consumptionL100: 0, co2GKm: 0,
    previousOwners: 1, accidentFree: true, inspectionValidUntil: '2025-08',
    fullServiceHistory: true, warranty: false, financingAvailable: true,
    images: img('Tesla Model 3 LR'), sellerType: 'DEALER', dealerName: 'EV Mobility Greifswald',
    latitude: 54.0865, longitude: 13.3923, postalCode: '17489', city: 'Greifswald', country: 'DE',
  },
  {
    providerListingId: 'demo-0008',
    make: 'Hyundai', model: 'i30 N', variant: 'Performance', title: 'Hyundai i30 N Performance',
    price: 28900, year: 2021, firstRegistration: '2021-04', mileage: 44700,
    powerKw: 206, powerHp: 280, fuelType: 'PETROL', transmission: 'MANUAL', drivetrain: 'FWD',
    bodyType: 'HATCHBACK', doors: 5, seats: 5, color: 'Performance Blue', interior: 'Stoff/Leder',
    features: ['N-Sportsitze', 'e-LSD', 'Klappenauspuff'], consumptionL100: 8.5, co2GKm: 194,
    displacementCcm: 1998, previousOwners: 2, accidentFree: true, inspectionValidUntil: '2026-04',
    fullServiceHistory: false, warranty: false, financingAvailable: true,
    images: img('Hyundai i30 N'), sellerType: 'PRIVATE',
    latitude: 53.5575, longitude: 13.2610, postalCode: '17033', city: 'Neubrandenburg', country: 'DE',
  },
  {
    providerListingId: 'demo-0009',
    make: 'Mercedes-Benz', model: 'C 220 d', variant: 'T-Modell Avantgarde', title: 'Mercedes C 220 d T-Modell',
    price: 38900, year: 2022, firstRegistration: '2022-05', mileage: 41800,
    powerKw: 147, powerHp: 200, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'RWD',
    bodyType: 'WAGON', doors: 5, seats: 5, color: 'Obsidianschwarz', interior: 'Leder Artico',
    features: ['MBUX', 'AHK', 'LED High Performance', 'Totwinkel'], consumptionL100: 5.0, co2GKm: 131,
    displacementCcm: 1993, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-05',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Mercedes C220d T'), sellerType: 'DEALER', dealerName: 'Mercedes-Benz Kiel',
    latitude: 54.3233, longitude: 10.1228, postalCode: '24103', city: 'Kiel', country: 'DE',
  },
  {
    providerListingId: 'demo-0010',
    make: 'BMW', model: 'X3', variant: 'xDrive30d M Sport', title: 'BMW X3 xDrive30d M Sport',
    price: 42500, year: 2020, firstRegistration: '2020-10', mileage: 92300,
    powerKw: 210, powerHp: 286, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'SUV', doors: 5, seats: 5, color: 'Sophistograu', interior: 'Leder Vernasca',
    features: ['Pano', 'AHK', 'HUD', 'ACC'], consumptionL100: 6.5, co2GKm: 172,
    displacementCcm: 2993, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-10',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('BMW X3 30d'), sellerType: 'DEALER', dealerName: 'BMW Niederlassung Hamburg',
    latitude: 53.5626, longitude: 10.0135, postalCode: '22083', city: 'Hamburg', country: 'DE',
  },
  {
    providerListingId: 'demo-0011',
    make: 'Fiat', model: '500', variant: '1.0 Hybrid Lounge', title: 'Fiat 500 Hybrid',
    price: 11490, year: 2021, firstRegistration: '2021-07', mileage: 28600,
    powerKw: 51, powerHp: 70, fuelType: 'HYBRID', transmission: 'MANUAL', drivetrain: 'FWD',
    bodyType: 'HATCHBACK', doors: 3, seats: 4, color: 'Gelato Weiß', interior: 'Stoff',
    features: ['Klima', 'CarPlay'], consumptionL100: 5.1, co2GKm: 118,
    displacementCcm: 999, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-07',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Fiat 500 Hybrid'), sellerType: 'DEALER', dealerName: 'Stadtauto Rostock',
    latitude: 54.0887, longitude: 12.1332, postalCode: '18057', city: 'Rostock', country: 'DE',
  },
  {
    providerListingId: 'demo-0012',
    make: 'Volvo', model: 'V60', variant: 'B4 Plus Dark', title: 'Volvo V60 B4 Mild-Hybrid',
    price: 35700, year: 2022, firstRegistration: '2022-09', mileage: 36900,
    powerKw: 145, powerHp: 197, fuelType: 'HYBRID', transmission: 'AUTOMATIC', drivetrain: 'FWD',
    bodyType: 'WAGON', doors: 5, seats: 5, color: 'Denim Blue', interior: 'Leder Charcoal',
    features: ['Pilot Assist', 'Harman Kardon', 'AHK'], consumptionL100: 6.3, co2GKm: 144,
    displacementCcm: 1969, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-09',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Volvo V60 B4'), sellerType: 'DEALER', dealerName: 'Volvo Center Bremen',
    latitude: 53.0793, longitude: 8.8017, postalCode: '28195', city: 'Bremen', country: 'DE',
  },
  {
    providerListingId: 'demo-0013',
    make: 'Cupra', model: 'Formentor', variant: 'VZ 2.0 TSI 4Drive', title: 'Cupra Formentor VZ',
    price: 39900, year: 2022, firstRegistration: '2022-06', mileage: 33500,
    powerKw: 228, powerHp: 310, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'SUV', doors: 5, seats: 5, color: 'Petrol Blau Matt', interior: 'Leder Petrol',
    features: ['Brembo', 'Beats', 'Matrix-LED'], consumptionL100: 8.0, co2GKm: 182,
    displacementCcm: 1984, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-06',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Cupra Formentor VZ'), sellerType: 'DEALER', dealerName: 'Cupra Garage Berlin',
    latitude: 52.5200, longitude: 13.4050, postalCode: '10115', city: 'Berlin', country: 'DE',
  },
  {
    providerListingId: 'demo-0014',
    make: 'Ford', model: 'Focus', variant: 'ST X 2.3 EcoBoost', title: 'Ford Focus ST X',
    price: 26900, year: 2020, firstRegistration: '2020-08', mileage: 67800,
    powerKw: 206, powerHp: 280, fuelType: 'PETROL', transmission: 'MANUAL', drivetrain: 'FWD',
    bodyType: 'HATCHBACK', doors: 5, seats: 5, color: 'Ford Performance Blau', interior: 'Recaro Leder',
    features: ['Recaro', 'B&O', 'LSD'], consumptionL100: 8.6, co2GKm: 196,
    displacementCcm: 2261, previousOwners: 2, accidentFree: true, inspectionValidUntil: '2026-08',
    fullServiceHistory: true, warranty: false, financingAvailable: true,
    images: img('Ford Focus ST'), sellerType: 'DEALER', dealerName: 'Ford Store Hannover',
    latitude: 52.3759, longitude: 9.7320, postalCode: '30159', city: 'Hannover', country: 'DE',
  },
  {
    providerListingId: 'demo-0015',
    make: 'Mini', model: 'Cooper S', variant: 'Classic Trim', title: 'Mini Cooper S 3-Türer',
    price: 23400, year: 2021, firstRegistration: '2021-10', mileage: 35400,
    powerKw: 131, powerHp: 178, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'FWD',
    bodyType: 'HATCHBACK', doors: 3, seats: 4, color: 'British Racing Green', interior: 'Leder Carbon Black',
    features: ['LED', 'Pano', 'CarPlay'], consumptionL100: 6.4, co2GKm: 147,
    displacementCcm: 1998, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-10',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Mini Cooper S'), sellerType: 'DEALER', dealerName: 'Mini Hamburg City',
    latitude: 53.5450, longitude: 9.9800, postalCode: '20457', city: 'Hamburg', country: 'DE',
  },
  {
    providerListingId: 'demo-0016',
    make: 'Volkswagen', model: 'T-Roc', variant: '1.5 TSI Life', title: 'VW T-Roc 1.5 TSI',
    price: 22900, year: 2021, firstRegistration: '2021-03', mileage: 52300,
    powerKw: 110, powerHp: 150, fuelType: 'PETROL', transmission: 'MANUAL', drivetrain: 'FWD',
    bodyType: 'SUV', doors: 5, seats: 5, color: 'Ravennablau', interior: 'Stoff',
    features: ['ACC', 'App-Connect', 'PDC'], consumptionL100: 6.0, co2GKm: 137,
    displacementCcm: 1498, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-03',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('VW T-Roc'), sellerType: 'DEALER', dealerName: 'VW Zentrum Schwerin',
    latitude: 53.6280, longitude: 11.4148, postalCode: '19055', city: 'Schwerin', country: 'DE',
  },
  {
    providerListingId: 'demo-0017',
    make: 'BMW', model: '118i', variant: 'Advantage', title: 'BMW 118i — sehr hohe Laufleistung',
    price: 9900, year: 2016, firstRegistration: '2016-04', mileage: 218000,
    powerKw: 100, powerHp: 136, fuelType: 'PETROL', transmission: 'MANUAL', drivetrain: 'RWD',
    bodyType: 'HATCHBACK', doors: 5, seats: 5, color: 'Alpinweiß', interior: 'Stoff',
    features: ['Klima', 'PDC'], consumptionL100: 5.9, co2GKm: 138,
    displacementCcm: 1499, previousOwners: 4, accidentFree: null, inspectionValidUntil: '2025-04',
    fullServiceHistory: false, warranty: false, financingAvailable: false,
    images: img('BMW 118i'), sellerType: 'PRIVATE',
    latitude: 54.0865, longitude: 12.1250, postalCode: '18069', city: 'Rostock', country: 'DE',
  },
  {
    providerListingId: 'demo-0018',
    make: 'Audi', model: 'RS3', variant: 'Sportback — Preis prüfen', title: 'Audi RS3 Sportback (auffällig günstig)',
    price: 29900, year: 2021, firstRegistration: '2021-09', mileage: 58000,
    powerKw: 294, powerHp: 400, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'HATCHBACK', doors: 5, seats: 5, color: 'Kyalamigrün',
    features: ['RS-Abgasanlage', 'Pano'], consumptionL100: 8.8, co2GKm: 201,
    displacementCcm: 2480, previousOwners: 3, accidentFree: null,
    fullServiceHistory: false, warranty: false, financingAvailable: false,
    images: img('Audi RS3'), sellerType: 'PRIVATE',
    latitude: 52.5065, longitude: 13.3320, postalCode: '10623', city: 'Berlin', country: 'DE',
  },
  {
    providerListingId: 'demo-0019',
    make: 'Hyundai', model: 'IONIQ 5', variant: '77.4 kWh Techniq', title: 'Hyundai IONIQ 5 Techniq',
    price: 37900, year: 2023, firstRegistration: '2023-01', mileage: 24800,
    powerKw: 168, powerHp: 228, fuelType: 'ELECTRIC', transmission: 'AUTOMATIC', drivetrain: 'RWD',
    bodyType: 'SUV', doors: 5, seats: 5, color: 'Gravity Gold Matt', interior: 'Öko-Leder',
    features: ['800V-Laden', 'HUD', 'V2L'], consumptionL100: 0, co2GKm: 0,
    previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-01',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Hyundai IONIQ 5'), sellerType: 'DEALER', dealerName: 'EV Mobility Greifswald',
    latitude: 54.0930, longitude: 13.3878, postalCode: '17491', city: 'Greifswald', country: 'DE',
  },
  {
    providerListingId: 'demo-0020',
    make: 'Toyota', model: 'GR86', variant: '2.4', title: 'Toyota GR86',
    price: 33900, year: 2023, firstRegistration: '2023-04', mileage: 12400,
    powerKw: 172, powerHp: 234, fuelType: 'PETROL', transmission: 'MANUAL', drivetrain: 'RWD',
    bodyType: 'COUPE', doors: 2, seats: 4, color: 'Ignition Red', interior: 'Stoff/Alcantara',
    features: ['Torsen-LSD', 'LED'], consumptionL100: 8.7, co2GKm: 198,
    displacementCcm: 2387, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-04',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Toyota GR86'), sellerType: 'DEALER', dealerName: 'Toyota Lübeck',
    latitude: 53.8560, longitude: 10.6800, postalCode: '23558', city: 'Lübeck', country: 'DE',
  },
  {
    providerListingId: 'demo-0021',
    make: 'Opel', model: 'Corsa', variant: '1.2 Edition', title: 'Opel Corsa 1.2 — Daten unvollständig',
    price: 13900, year: 2022, mileage: 19800,
    powerKw: 55, powerHp: 75, fuelType: 'PETROL', transmission: 'MANUAL',
    bodyType: 'HATCHBACK', doors: 5, color: 'Rot',
    images: img('Opel Corsa'), sellerType: 'DEALER', dealerName: 'Autopark Neubrandenburg',
    latitude: 53.5620, longitude: 13.2745, postalCode: '17034', city: 'Neubrandenburg', country: 'DE',
  },
  {
    providerListingId: 'demo-0022',
    make: 'Kia', model: 'Sorento', variant: '2.2 CRDi AWD Platinum', title: 'Kia Sorento 7-Sitzer',
    price: 41900, year: 2021, firstRegistration: '2021-12', mileage: 55600,
    powerKw: 148, powerHp: 202, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'SUV', doors: 5, seats: 7, color: 'Essence Braun', interior: 'Leder Nappa',
    features: ['7 Sitze', 'AHK', 'Bose', '360°-Kamera'], consumptionL100: 6.9, co2GKm: 180,
    displacementCcm: 2151, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2026-12',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Kia Sorento'), sellerType: 'DEALER', dealerName: 'Kia Autohaus Stralsund',
    latitude: 54.3155, longitude: 13.0900, postalCode: '18439', city: 'Stralsund', country: 'DE',
  },
  {
    providerListingId: 'demo-0023',
    make: 'Volkswagen', model: 'Multivan', variant: 'T6.1 2.0 TDI Comfortline', title: 'VW T6.1 Multivan',
    price: 47800, year: 2021, firstRegistration: '2021-06', mileage: 84200,
    powerKw: 146, powerHp: 199, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'FWD',
    bodyType: 'VAN', doors: 4, seats: 7, color: 'Candy-Weiß', interior: 'Stoff',
    features: ['2x Schiebetür', 'Standheizung', 'AHK'], consumptionL100: 7.3, co2GKm: 192,
    displacementCcm: 1968, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-06',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('VW T6.1 Multivan'), sellerType: 'DEALER', dealerName: 'Nutzfahrzeuge Rostock',
    latitude: 54.1050, longitude: 12.0990, postalCode: '18119', city: 'Rostock', country: 'DE',
  },
  {
    providerListingId: 'demo-0024',
    make: 'Suzuki', model: 'Swift Sport', variant: '1.4 Boosterjet Hybrid', title: 'Suzuki Swift Sport',
    price: 18990, year: 2022, firstRegistration: '2022-08', mileage: 27300,
    powerKw: 95, powerHp: 129, fuelType: 'HYBRID', transmission: 'MANUAL', drivetrain: 'FWD',
    bodyType: 'HATCHBACK', doors: 5, seats: 4, color: 'Champion Yellow', interior: 'Stoff/Sportsitze',
    features: ['LED', 'ACC', 'Keyless'], consumptionL100: 5.6, co2GKm: 127,
    displacementCcm: 1373, previousOwners: 1, accidentFree: true, inspectionValidUntil: '2027-08',
    fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Suzuki Swift Sport'), sellerType: 'DEALER', dealerName: 'Suzuki Wismar',
    latitude: 53.8880, longitude: 11.4650, postalCode: '23970', city: 'Wismar', country: 'DE',
  },

  {
    providerListingId: 'demo-0101', make: 'Porsche', model: 'Panamera', variant: 'Turbo S E-Hybrid', title: 'Porsche Panamera Turbo S E-Hybrid',
    price: 132900, year: 2022, firstRegistration: '2022-07', mileage: 23800, powerKw: 515, powerHp: 700, fuelType: 'PLUGIN_HYBRID', transmission: 'AUTOMATIC', drivetrain: 'AWD',
    bodyType: 'SEDAN', doors: 5, seats: 4, color: 'Vulkangrau', interior: 'Leder Club', features: ['Sport Chrono', 'Keramikbremse', 'Matrix-LED', 'Luftfahrwerk'], consumptionL100: 3.2, co2GKm: 73, displacementCcm: 3996, previousOwners: 1, accidentFree: true, fullServiceHistory: true, warranty: true, financingAvailable: true,
    images: img('Porsche Panamera Turbo S E-Hybrid'), sellerType: 'DEALER', dealerName: 'Porsche Zentrum Hamburg', latitude: 53.55, longitude: 9.99, postalCode: '20095', city: 'Hamburg', country: 'DE',
    rawData: { imageSource: 'DEMO Platzhalter via placehold.co', imageLicense: 'Demo placeholder' },
  },
  {
    providerListingId: 'demo-0102', make: 'Porsche', model: '911', variant: 'Carrera 4S', title: 'Porsche 911 Carrera 4S',
    price: 124900, year: 2021, firstRegistration: '2021-05', mileage: 18400, powerKw: 331, powerHp: 450, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'AWD', bodyType: 'COUPE', doors: 2, seats: 4, color: 'Kreide', features: ['Sport Chrono', 'PASM', 'Bose'], consumptionL100: 9.7, co2GKm: 220, displacementCcm: 2981, previousOwners: 1, accidentFree: true, fullServiceHistory: true, warranty: true, financingAvailable: true, images: img('Porsche 911 Carrera 4S'), sellerType: 'DEALER', dealerName: 'Porsche Zentrum Lübeck', latitude: 53.87, longitude: 10.69, postalCode: '23552', city: 'Lübeck', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
  {
    providerListingId: 'demo-0103', make: 'BMW', model: 'M5', variant: 'CS', title: 'BMW M5 CS',
    price: 154900, year: 2022, firstRegistration: '2022-02', mileage: 16200, powerKw: 467, powerHp: 635, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'AWD', bodyType: 'SEDAN', doors: 4, seats: 4, color: 'Frozen Deep Green', interior: 'Carbon-Schalen', features: ['Carbon-Keramik', 'M Driver Package', 'Laserlicht'], consumptionL100: 11.3, co2GKm: 258, displacementCcm: 4395, previousOwners: 1, accidentFree: true, fullServiceHistory: true, warranty: true, financingAvailable: true, images: img('BMW M5 CS'), sellerType: 'DEALER', dealerName: 'BMW M Spezialist Hamburg', latitude: 53.56, longitude: 10.01, postalCode: '22083', city: 'Hamburg', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
  {
    providerListingId: 'demo-0104', make: 'BMW', model: '330d', variant: 'Coupé E92', title: 'BMW 330d Coupé E92',
    price: 18900, year: 2011, firstRegistration: '2011-04', mileage: 148000, powerKw: 180, powerHp: 245, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'RWD', bodyType: 'COUPE', doors: 2, seats: 4, color: 'Le Mans Blau', features: ['M-Paket', 'Navi Professional', 'Xenon'], consumptionL100: 6.2, co2GKm: 164, displacementCcm: 2993, previousOwners: 3, accidentFree: true, fullServiceHistory: false, warranty: false, financingAvailable: false, images: img('BMW 330d Coupe E92'), sellerType: 'PRIVATE', latitude: 53.63, longitude: 11.41, postalCode: '19053', city: 'Schwerin', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
  {
    providerListingId: 'demo-0105', make: 'Audi', model: 'RS5', variant: 'B9 Coupé', title: 'Audi RS5 Coupé B9',
    price: 57900, year: 2019, firstRegistration: '2019-09', mileage: 58500, powerKw: 331, powerHp: 450, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'AWD', bodyType: 'COUPE', doors: 2, seats: 4, color: 'Nardograu', features: ['RS Sportabgasanlage', 'Virtual Cockpit', 'Matrix-LED'], consumptionL100: 8.7, co2GKm: 197, displacementCcm: 2894, previousOwners: 2, accidentFree: true, fullServiceHistory: true, warranty: true, financingAvailable: true, images: img('Audi RS5 B9 Coupe'), sellerType: 'DEALER', dealerName: 'Audi Sport Partner Berlin', latitude: 52.52, longitude: 13.40, postalCode: '10115', city: 'Berlin', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
  {
    providerListingId: 'demo-0106', make: 'Audi', model: 'A5', variant: '3.0 TDI quattro', title: 'Audi A5 3.0 TDI quattro',
    price: 22400, year: 2015, firstRegistration: '2015-06', mileage: 124000, powerKw: 180, powerHp: 245, fuelType: 'DIESEL', transmission: 'AUTOMATIC', drivetrain: 'AWD', bodyType: 'COUPE', doors: 2, seats: 4, color: 'Daytonagrau', features: ['S line', 'B&O', 'Xenon Plus'], consumptionL100: 5.9, co2GKm: 155, displacementCcm: 2967, previousOwners: 2, accidentFree: true, fullServiceHistory: true, warranty: false, financingAvailable: true, images: img('Audi A5 3.0 TDI'), sellerType: 'DEALER', dealerName: 'Audi Partner Rostock', latitude: 54.09, longitude: 12.14, postalCode: '18055', city: 'Rostock', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
  {
    providerListingId: 'demo-0107', make: 'Mercedes-Benz', model: 'C 63 AMG', variant: 'S W205', title: 'Mercedes-AMG C 63 S W205',
    price: 61900, year: 2018, firstRegistration: '2018-08', mileage: 67200, powerKw: 375, powerHp: 510, fuelType: 'PETROL', transmission: 'AUTOMATIC', drivetrain: 'RWD', bodyType: 'SEDAN', doors: 4, seats: 5, color: 'Selenitgrau', features: ['Performance Abgasanlage', 'AMG Driver Package', 'Burmester'], consumptionL100: 10.8, co2GKm: 244, displacementCcm: 3982, previousOwners: 2, accidentFree: true, fullServiceHistory: true, warranty: true, financingAvailable: true, images: img('Mercedes AMG C63 S W205'), sellerType: 'DEALER', dealerName: 'AMG Performance Center Kiel', latitude: 54.32, longitude: 10.12, postalCode: '24103', city: 'Kiel', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
  {
    providerListingId: 'demo-0108', make: 'Volvo', model: 'XC60', variant: 'B5 AWD Inscription', title: 'Volvo XC60 B5 AWD',
    price: 42900, year: 2022, firstRegistration: '2022-11', mileage: 35900, powerKw: 184, powerHp: 250, fuelType: 'HYBRID', transmission: 'AUTOMATIC', drivetrain: 'AWD', bodyType: 'SUV', doors: 5, seats: 5, color: 'Denim Blue', features: ['Pilot Assist', 'Bowers & Wilkins', 'AHK'], consumptionL100: 7.2, co2GKm: 164, displacementCcm: 1969, previousOwners: 1, accidentFree: true, fullServiceHistory: true, warranty: true, financingAvailable: true, images: img('Volvo XC60 B5 AWD'), sellerType: 'DEALER', dealerName: 'Volvo Zentrum Schwerin', latitude: 53.63, longitude: 11.40, postalCode: '19053', city: 'Schwerin', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
  {
    providerListingId: 'demo-0109', make: 'Kia', model: 'EV6', variant: 'GT-Line AWD', title: 'Kia EV6 GT-Line AWD',
    price: 44900, year: 2023, firstRegistration: '2023-03', mileage: 18800, powerKw: 239, powerHp: 325, fuelType: 'ELECTRIC', transmission: 'AUTOMATIC', drivetrain: 'AWD', bodyType: 'SUV', doors: 5, seats: 5, color: 'Moonscape Matt', features: ['800V-Laden', 'Wärmepumpe', 'HUD'], consumptionL100: 0, co2GKm: 0, previousOwners: 1, accidentFree: true, fullServiceHistory: true, warranty: true, financingAvailable: true, images: img('Kia EV6 GT-Line AWD'), sellerType: 'DEALER', dealerName: 'Kia Autohaus Stralsund', latitude: 54.31, longitude: 13.08, postalCode: '18439', city: 'Stralsund', country: 'DE', rawData: { imageSource: 'DEMO Platzhalter via placehold.co' },
  },
]
